version: "2"
services:
  app:
    container_name: knockknock-app
    environment:
      - APP_PORT=5000
      - MONGO_HOST=mongo
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"