[app]
port="APP_PORT"

[slack]
clientId="SLACK_CLIENT_ID"
clientSecret="SLACK_CLIENT_SECRET"
verificationToken="SLACK_VERIFICATION_TOKEN"

[mongo]
host="MONGO_HOST"
port="MONGO_PORT"
dbName="MONGO_DB_NAME"

[crypto]
encryptionKey="CRYPTO_ENCRYPTION_KEY"